version: '3'

services:
  web-app:
    build: .
    container_name: web-app
    hostname: web-app
    environment:
      - PYTHONUNBUFFERED=1
      - DJANGO_SETTINGS_MODULE=education_platform_for_pythoneers.settings_docker
    entrypoint: [ "/bin/sh","-c" ]
    links:
      - selenium
    command:
      - |
        python manage.py makemigrations
        python manage.py migrate && python manage.py migrate --run-syncdb
        python setup_docker.py
        python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:12.5
    container_name: db
    hostname: db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 30s
      retries: 6
    restart: always

  selenium:
    image: selenium/standalone-chrome-debug:3.7.1
    ports:
      - "4444:4444"
    restart: always
